remote_theme: thelehhman/texture
show_excerpts: true
minima:
  date_format: "%-d  %b %Y"
texture:
  title: Joel Clemence
  tagline: Developer. 
  date_format: "%-d %b %Y"
  style: blue
  showNav: true

  social_links:
    twitter: thisisjoelc
    github:  JoelClemence
