remote_theme: thelehhman/texture
show_excerpts: true
texture:
  title: Joel Clemence
  tagline: Developer. 
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true

  social_links:
    twitter: thisisjoelc
    github:  JoelClemence
