remote_theme: thelehhman/texture
texture:
  title: Joel Clemence
  tagline: Developer. 
  date_format: "%b %-d, %Y"
  style: blue
  show_excerpts: true
  showNav: true

  social_links:
    twitter: thisisjoelc
    github:  JoelClemence
